spring:
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_LOGIN}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}